// Language actions
export const FETCH_LANGUAGE_REQUEST = 'FETCH_LANGUAGE_REQUEST';
export const FETCH_LANGUAGE_SUCCESS = 'FETCH_LANGUAGE_SUCCESS';
export const FETCH_LANGUAGE_FAILURE = 'FETCH_LANGUAGE_FAILURE';

// Categories actions
export const FETCH_CATEGORY_REQUEST = 'FETCH_CATEGORY_REQUEST';
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';
export const FETCH_CATEGORY_FAILURE = 'FETCH_CATEGORY_FAILURE';

// Users actions
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
export const UPDATE_USER_STATUS = "UPDATE_USER_STATUS";

//Transction actions
export const FETCH_USERS_TRANSCTION = 'FETCH_USERS_TRANSCTION';
export const FETCH_USERS_TRANSCTION_SUCCESS = 'FETCH_USERS_TRANSCTION_SUCCESS';
export const FETCH_USERS_TRANSCTION_FAILURE = 'FETCH_USERS_TRANSCTION_FAILURE';

//Filter actions
export const FETCH_FILTER_TRANSCTION = 'FETCH_FILTER_TRANSCTION';
export const FETCH_FILTER_TRANSCTION_SUCCESS = 'FETCH_FILTER_TRANSCTION_SUCCESS';
export const FETCH_FILTER_TRANSCTION_FAILURE = 'FETCH_FILTER_TRANSCTION_FAILURE';

//Invoice actions
export const FETCH_USERS_INVOICE = 'FETCH_USERS_INVOICE';
export const FETCH_USERS_INVOICE_SUCCESS = 'FETCH_USERS_INVOICE_SUCCESS';
export const FETCH_USERS_INVOICE_FAILURE = 'FETCH_USERS_INVOICE_FAILURE';

// Invoice Filter actions
export const FETCH_FILTER_INVOICE = 'FETCH_FILTER_INVOICE';
export const FETCH_FILTER_INVOICE_SUCCESS = 'FETCH_FILTER_INVOICE_SUCCESS';
export const FETCH_FILTER_INVOICE_FAILURE = 'FETCH_FILTER_INVOICE_FAILURE';